-- ==========================================================
-- Actualiza el catalogo con la info del PDF "CATALAGO MAISON ZADACA -
-- ACTUALIZADO - SEPTIEMBRE 2026" (74 paginas, perfumeria arabe +
-- un puñado de diseñador al final): precio de frasco completo, precios
-- de decant 3/5/10ml, notas olfativas (los "pills" de colores del PDF) y
-- a que perfume de diseñador imita cada uno ("DUP: ... de ..." en el PDF).
--
-- REQUISITO: corre primero supabase/migrations/0017_inspirado_en.sql
-- (agrega la columna inspirado_en) -- este script ya asume que existe.
--
-- Como se armo: se extrajeron a mano las 74 paginas del PDF (son fotos,
-- pdftotext -layout sale ilegible por las cajas de texto superpuestas) y
-- se cruzaron contra el catalogo real via la anon key de Supabase, por
-- (marca, nombre) normalizado. El mismo perfume suele tener DOS filas --
-- una de frasco completo (es_decant=false) y una de decant
-- (es_decant=true, ver migracion 0016) -- así que muchos perfumes generan
-- dos updates o dos inserts (uno por fila).
--
-- Reglas seguidas para no perder ni pisar datos:
--  - Si el frasco ya tenia el mismo precio que el PDF, no se toca la
--    columna precio_tienda_regular (solo se actualizan notas/inspirado_en).
--  - En decants, solo se actualiza la talla (3/5/10 ml) que el PDF
--    realmente muestra -- las demas quedan como estaban.
--  - familia_olfativa solo se llena si estaba en null (nunca pisa un valor
--    ya cargado a mano desde el admin) -- en este catalogo estaba null en
--    las 396 filas, asi que se llena en todas las que se tocan.
--  - notas_olfativas se reemplaza siempre con las notas del PDF (join de
--    los "pills" de color, en el mismo orden que aparecen).
--  - Perfumes que el PDF marca "SOLD OUT" SI se actualizan (traen info
--    real), pero quedan marcados en el reporte de revision para que el
--    dueño decida si corresponde reactivarlos/tocar estado o stock.
--  - Nuevos productos (sin ninguna fila existente): se insertan con
--    slug generado igual que generarSlug() del admin (marca+nombre,
--    normalizado), sufijo "-decant" para la fila de decant, mililitros=100
--    (capacidad del frasco fuente), precio_tienda_regular=precio_consolidado_fijo
--    = la talla de decant mas grande disponible cuando no hay precio de
--    frasco (mismo criterio que usa el modal de decants del admin, ver
--    admin.js linea ~685), activo=true, margen_aplicado=true,
--    estado='Disponible'.
--
-- Varias marcas del PDF no coincidian con como estan cargadas en el
-- catalogo real y se corrigieron durante el cruce (ver
-- supabase/catalogo_pdf_revision_pendiente.md para el detalle):
--   - La linea "Rome" (Imagine/Paradox/Extradose/Pour Home) es de
--     Bharara, no de un "Fragrance World" generico.
--   - La linea "Rayhaan"/"Rayhaam" (Aquatica/Tropical Vibe/Wolf) es de
--     Lattafa.
--   - "Nebula"/"King Of Kings Nebula" es de la marca "King of Kings".
--   - "His Confession" coincide con "HIS Confesion" de Rasasi.
--   - "Nitro White" se asumio Rasasi (ahi viven las otras Nitro).
--   - Un puñado de productos sin ninguna marca legible en la foto se
--     cargaron con marca 'Por Definir' (convencion ya usada en el
--     catalogo real, ver migracion 0007) en vez de adivinar.
--
-- Revisar supabase/catalogo_pdf_revision_pendiente.md ANTES de correr
-- este script -- lista todas las entradas de baja confianza (nombres
-- ambiguos, posibles duplicados del PDF, productos marcados SOLD OUT,
-- decants sin precio legible, etc).
--
-- Ejecutar UNA SOLA VEZ en el SQL Editor de Supabase.
-- ==========================================================

/* ================================================================
   1. ACTUALIZACIONES -- productos que ya existen en el catalogo real
   ================================================================ */

update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Avainillado, Ámbar, Cálido, Dulce, Aromático', inspirado_en = 'Ultra Male de Jean Paul Gaultier', familia_olfativa = 'Avainillado' where id = 1; -- Afnan 9PM (frasco) [p8]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Afrutado, Cítrico, Verde, Ámbar, Amaderado', inspirado_en = 'Y Eau de Parfum de Yves Saint Laurent', familia_olfativa = 'Afrutado' where id = 3; -- Afnan 9AM Dive (frasco) [p9]
update perfumes set precio_tienda_regular = 165, notas_olfativas = 'Cálido Especiado, Avainillado, Cálido, Ámbar, Amaderado', inspirado_en = 'Ultra Male Elixir de Jean Paul Gaultier', familia_olfativa = 'Cálido Especiado' where id = 6; -- Afnan 9PM Elixir (frasco) [p8]
update perfumes set precio_tienda_regular = 200, notas_olfativas = 'Cálido Especiado, Afrutado, Cálido, Dulce, Aromático', familia_olfativa = 'Cálido Especiado' where id = 9; -- Afnan 9PM Night Out (frasco) [p9]
update perfumes set notas_olfativas = 'Afrutados, Dulce, Ozónico, Atalcado, Avainillado', inspirado_en = 'Erba Pura de Xerjoff', familia_olfativa = 'Afrutados' where id = 19; -- Al Haramain Haramain Amber Oud (frasco) [p51]
update perfumes set precio_tienda_regular = 165, notas_olfativas = 'Cítrico, Afrutado, Amaderado, Cuero, Dulce', inspirado_en = 'Aventus de Creed', familia_olfativa = 'Cítrico' where id = 24; -- Armaf Club De Nuit Intense Man (frasco) [p16]
update perfumes set precio_tienda_regular = 175, notas_olfativas = 'Ámbar, Aromático, Frescos, Cítrico, Almizcado', inspirado_en = 'Sauvage de Dior', familia_olfativa = 'Ámbar' where id = 28; -- Armaf Club De Nuit Urban Man Elixir (frasco) [p16]
update perfumes set precio_tienda_regular = 185, notas_olfativas = 'Afrutados, Aromático, Frescos, Cítrico, Vainilla', familia_olfativa = 'Afrutados' where id = 30; -- Armaf Club De Nuit Maleka (frasco) [p17]
update perfumes set precio_tienda_regular = 185, notas_olfativas = 'Cítrico, Cálido, Aromático, Ámbar, Dulce', inspirado_en = 'Bleu de Chanel Eau de Parfum', familia_olfativa = 'Cítrico' where id = 32; -- Armaf Club De Nuit Iconic (frasco) [p17]
update perfumes set precio_tienda_regular = 175, notas_olfativas = 'Aromático, Fresco Especiado, Cítrico, Ámbar, Amaderado', inspirado_en = 'Invictus Platinum de Paco Rabanne', familia_olfativa = 'Aromático' where id = 35; -- Armaf Odyssey Aqua (frasco) [p11]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Avainillado, Ámbar, Coco, Tropical, Dulce', inspirado_en = 'Le Beau Eau de Toilette de Jean Paul Gaultier', familia_olfativa = 'Avainillado' where id = 36; -- Armaf Odyssey Artisto (frasco) [p14]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Cítrico, Dulce, Caramelo, Ámbar, Amaderado', inspirado_en = 'Afternoon Swim de Louis Vuitton', familia_olfativa = 'Cítrico' where id = 39; -- Armaf Odyssey Limoni (frasco) [p13]
-- OJO: NO se toca el precio acá -- id=40 es la variante de 200ml ("Odyssey Mandarin SKY",
-- ya vale 218/168), y el precio de S/150 del PDF es claramente el de una botella de 100ml
-- que no existe como fila propia en el catálogo real (solo hay 200ml, "Elixir Limited
-- Edition" y "Vintage Edition" en 100ml) -- aplicarle el precio de 100ml a esta fila de
-- 200ml sería un dato incorrecto, además de violar chk_precio_consolidado_menor (150 <
-- precio_consolidado_fijo actual de 168). Las notas/DUP sí valen igual sin importar el
-- tamaño del frasco, así que esas se actualizan igual.
update perfumes set notas_olfativas = 'Cítrico, Aromático, Caramelo, Avainillado, Ámbar', inspirado_en = 'Scandal Pour Homme de Jean Paul Gaultier', familia_olfativa = 'Cítrico' where id = 40; -- Armaf Odyssey Mandarin Sky (frasco) [p12]
update perfumes set precio_tienda_regular = 180, notas_olfativas = 'Cítrico, Dulce, Caramelo, Ámbar', inspirado_en = 'Scandal Pour Homme Le Parfum de Jean Paul Gaultier', familia_olfativa = 'Cítrico' where id = 41; -- Armaf Odyssey Mandarin Sky Elixir (frasco) [p12]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Canela, Avainillado, Tabaco, Dulce, Aromático', inspirado_en = 'Ultra Male de Jean Paul Gaultier', familia_olfativa = 'Canela' where id = 43; -- Armaf Odyssey Spectra (frasco) [p11]
update perfumes set precio_tienda_regular = 245, notas_olfativas = 'Afrutados, Dulce, Azónico, Atalcado, Avainillado', familia_olfativa = 'Afrutados' where id = 50; -- Bharara Bharara King (frasco) [p53]
update perfumes set precio_tienda_regular = 170, notas_olfativas = 'Aromático, Fresco, Amaderado, Rosas, Herbal', familia_olfativa = 'Aromático' where id = 53; -- Bharara Rome Pour Home (frasco) [p56]
update perfumes set precio_tienda_regular = 400, notas_olfativas = 'Cálido Especiado, Amaderado, Dulce, Afrutados, Avainillado', familia_olfativa = 'Cálido Especiado' where id = 54; -- Bharara Pharaoh Ramesses (frasco) [p53]
update perfumes set precio_tienda_regular = 300, notas_olfativas = 'Cítrico, Afrutado, Fresco, Fresco Acuático, Cálido', familia_olfativa = 'Cítrico' where id = 61; -- Dolce & Gabbana Light Blue (frasco) [p71]
update perfumes set precio_tienda_regular = 550, notas_olfativas = 'Fresco, Mineral, Acuático, Azónico, Amaderado', familia_olfativa = 'Fresco' where id = 73; -- Jean Paul Gaultier Le Beau Le Parfum Intense (frasco) [p69]
-- precio_consolidado_fijo baja junto con precio_tienda_regular acá: esta fila no tenía
-- descuento de consolidado propio (ambos precios ya eran iguales, 420/420), así que bajar
-- solo el de tienda a 400 sin tocar el otro violaba chk_precio_consolidado_menor (420 >
-- 400). Se deja el mismo criterio (sin descuento propio) en vez de inventar uno nuevo --
-- si el dueño quiere un precio de consolidado más bajo, lo define con la Calculadora de
-- Márgenes.
update perfumes set precio_tienda_regular = 400, precio_consolidado_fijo = 400, notas_olfativas = 'Avainillado, Dulce, Aromático, Amielado, Ámbar', familia_olfativa = 'Avainillado' where id = 77; -- Jean Paul Gaultier Le Male Elixir (frasco) [p68]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Ámbar, Frescos Especiado, Amaderado, Tabaco, Dulce', inspirado_en = 'Sauvage Elixir de Dior', familia_olfativa = 'Ámbar' where id = 89; -- Lattafa Asad (frasco) [p38]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Avainillado, Cacao, Lavanda, Floral, Atalcado', inspirado_en = 'The Most Wanted Parfum de Azzaro', familia_olfativa = 'Avainillado' where id = 90; -- Lattafa Asad Bourbon (frasco) [p37]
update perfumes set precio_tienda_regular = 170, notas_olfativas = 'Ámbar, Avainillado, Amaderado, Fresco, Atalcado', familia_olfativa = 'Ámbar' where id = 91; -- Lattafa Asad Elixir (frasco) [p38]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Rosas, Oud, Ámbar, Florales, Avainillado', familia_olfativa = 'Rosas' where id = 93; -- Lattafa Amethyst (frasco) [p41]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Cálido Especiado, Pachulí, Fresco, Amaderado, Metálico', familia_olfativa = 'Cálido Especiado' where id = 94; -- Lattafa Oud For Glory (frasco) [p42]
update perfumes set precio_tienda_regular = 170, notas_olfativas = 'Avainillado, Atalcado, Amaderado, Coco, Afrutado', familia_olfativa = 'Avainillado' where id = 95; -- Lattafa Eclaire (frasco) [p43]
update perfumes set precio_tienda_regular = 165, notas_olfativas = 'Floral, Cítrico, Afrutado, Dulce, Avainillado', familia_olfativa = 'Floral' where id = 100; -- Lattafa Haya (frasco) [p44]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Afrutados, Canela, Almizcado, Cálido, Atalcado', familia_olfativa = 'Afrutados' where id = 101; -- Lattafa Hayaati (frasco) [p45]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Dulce, Cálido Especiado, Ámbar, Canela, Amaderado', inspirado_en = 'Angels'' Share de By Kilian', familia_olfativa = 'Dulce' where id = 103; -- Lattafa Khamrah (frasco) [p31]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Cálido Especiado, Dulce, Avainillado, Café, Canela', familia_olfativa = 'Cálido Especiado' where id = 104; -- Lattafa Khamrah Qahwa (frasco) [p31]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Ámbar, Cálido Especiado, Dulce, Tabaco, Amaderado', familia_olfativa = 'Ámbar' where id = 105; -- Lattafa Khamrah Dukhan (frasco) [p32]
update perfumes set precio_tienda_regular = 170, notas_olfativas = 'Avainillado, Atalcado, Dulce, Frutales, Almizcado', familia_olfativa = 'Avainillado' where id = 107; -- Lattafa Nebras (frasco) [p47]
update perfumes set precio_tienda_regular = 180, notas_olfativas = 'Avainillado, Atalcado, Amizclado, Dulce, Ámbar', familia_olfativa = 'Avainillado' where id = 116; -- Lattafa Nebras Elixir (frasco) [p47]
update perfumes set precio_tienda_regular = 140, notas_olfativas = 'Afrutados, Dulces, Frescos, Cítrico, Amaderados', familia_olfativa = 'Afrutados' where id = 117; -- Lattafa Qaed Al Fursan (frasco) [p19]
update perfumes set precio_tienda_regular = 140, notas_olfativas = 'Aromático, Ámbar, Frescos, Caramelo, Amaderados', inspirado_en = 'Eros de Versace', familia_olfativa = 'Aromático' where id = 119; -- Lattafa Qaed Untamed (frasco) [p20]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Afrutados, Frescos Especiado, Rosas, Tropical, Dulce', inspirado_en = 'Eden Juicy Apple de Kayali', familia_olfativa = 'Afrutados' where id = 125; -- Lattafa Sublime (frasco) [p40]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Avainillados, Dulce, Afrutados, Atalcados, Floral', inspirado_en = 'Yum Pistachio Gelato 33 de Kayali', familia_olfativa = 'Avainillados' where id = 127; -- Lattafa Yara Candy (frasco) [p35]
update perfumes set notas_olfativas = 'Avainillados, Caramelo, Afrutados, Atalcados, Floral', familia_olfativa = 'Avainillados' where id = 128; -- Lattafa Yara Elixir (frasco) [p36]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Amaderado, Pachulí, Caramelo, Cálido, Floral', familia_olfativa = 'Amaderado' where id = 129; -- Lattafa Yara Moi (frasco) [p37]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Tropical, Dulce, Avainillado, Floral, Atalcado', familia_olfativa = 'Tropical' where id = 131; -- Lattafa Yara Tous (frasco) [p36]
update perfumes set precio_tienda_regular = 200, notas_olfativas = 'Cítrico, Afrutado, Verde, Dulce, Floral', familia_olfativa = 'Cítrico' where id = 134; -- Lattafa Pride Art Of Universe (frasco) [p48]
update perfumes set precio_tienda_regular = 295, notas_olfativas = 'Ámbar, Avainillado, Dulce, Floral, Afrutado', familia_olfativa = 'Ámbar' where id = 144; -- Lattafa Pride Game Of Spades Wildcard (frasco) [p63]
update perfumes set precio_tienda_regular = 210, notas_olfativas = 'Cítrico, Atalcado, Dulce, Amaderado, Almizcado', familia_olfativa = 'Cítrico' where id = 147; -- Lattafa Pride Pisa (frasco) [p48]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Dulce, Atalcado, Fresco, Almendrado, Afrutado', inspirado_en = 'Good Girl Blush Elixir de Carolina Herrera', familia_olfativa = 'Dulce' where id = 176; -- Lattafa Noble Blush (frasco) [p41]
update perfumes set precio_tienda_regular = 160, notas_olfativas = 'Aromático, Dulce, Ámbar, Lavanda, Avainillado', familia_olfativa = 'Aromático' where id = 187; -- Lattafa The Kingdom (frasco) [p42]
update perfumes set precio_tienda_regular = 190, notas_olfativas = 'Tropical, Afrutado, Dulce, Cítrico, Coco', familia_olfativa = 'Tropical' where id = 195; -- Rasasi His Confession (frasco) [p61]
update perfumes set precio_tienda_regular = 175, notas_olfativas = 'Amaderado, Cítrico, Musgosos, Tarrosos, Afrutados', inspirado_en = 'Hacivat de Nishane', familia_olfativa = 'Amaderado' where id = 197; -- Rasasi Hawas Black (frasco) [p25]
update perfumes set precio_tienda_regular = 185, notas_olfativas = 'Avainillado, Aromático, Dulce, Ámbar, Amaderado', inspirado_en = 'Le Male Elixir de Jean Paul Gaultier', familia_olfativa = 'Avainillado' where id = 198; -- Rasasi Hawas Elixir (frasco) [p22]
update perfumes set precio_tienda_regular = 190, notas_olfativas = 'Aromático, Ámbar, Floral, Marino, Mineral', inspirado_en = 'Aventus/Sauvage/Baccarat Rouge (multi-ref)', familia_olfativa = 'Aromático' where id = 199; -- Rasasi Hawas Fire (frasco) [p25]
update perfumes set precio_tienda_regular = 170, notas_olfativas = 'Afrutados, Cítrico, Floral, Fresco, Aromático', inspirado_en = 'Invictus Aqua de Paco Rabanne', familia_olfativa = 'Afrutados' where id = 200; -- Rasasi Hawas Ice (frasco) [p22]
update perfumes set precio_tienda_regular = 175, notas_olfativas = 'Dulce, Coco, Amaderado, Verde, Avainillado', inspirado_en = 'Le Beau Paradise Garden de Jean Paul Gaultier', familia_olfativa = 'Dulce' where id = 203; -- Rasasi Hawas Tropical (frasco) [p24]
update perfumes set precio_tienda_regular = 185, notas_olfativas = 'Avainillado, Afrutados, Ámbar, Atalcado, Amaderado', inspirado_en = 'Donna Born In Roma Intense de Valentino', familia_olfativa = 'Avainillado' where id = 204; -- Rasasi Hawas Diva (frasco) [p26]
update perfumes set precio_tienda_regular = 580, notas_olfativas = 'Lavanda, Cálido, Aromático, Ámbar, Amaderado', familia_olfativa = 'Lavanda' where id = 206; -- Valentino Uomo Born In Roma Extradosis (frasco) [p66]
update perfumes set precio_tienda_regular = 165, notas_olfativas = 'Fresco Picante, Aromático, Agrios, Vainilla, Leñoso', familia_olfativa = 'Fresco Picante' where id = 218; -- Lattafa Khamrah Waha (frasco) [p32]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Dulce, Afrutado, Atalcado, Fresco, Amaderado', inspirado_en = 'Tribeca de Bond No. 9', familia_olfativa = 'Dulce' where id = 219; -- Lattafa Honor & Glory (frasco) [p40]
update perfumes set precio_tienda_regular = 200, notas_olfativas = 'Tropical, Afrutado, Dulce, Cítrico, Coco', familia_olfativa = 'Tropical' where id = 220; -- Lattafa Rayhaan Tropical Vibe (frasco) [p60]
update perfumes set precio_tienda_regular = 150, notas_olfativas = 'Café, Cacao, Dulce, Amielado, Avainillado', familia_olfativa = 'Café' where id = 227; -- Armaf Odyssey Coffee Toffee (frasco) [p14]
update perfumes set precio_tienda_regular = 160, notas_olfativas = 'Floral Blanco, Nardos, Amaderado, Dulce, Afrutado', familia_olfativa = 'Floral Blanco' where id = 232; -- Lattafa Fakhar Rose (frasco) [p44]
update perfumes set precio_tienda_regular = 160, notas_olfativas = 'Lactónico, Coco, Cacao, Dulce, Avainillado', familia_olfativa = 'Lactónico' where id = 235; -- Lattafa Eclaire Pistacho (frasco) [p43]
update perfumes set precio_tienda_regular = 160, notas_olfativas = 'Lavanda, Cálido, Amaderado, Aromático, Frescos', familia_olfativa = 'Lavanda' where id = 238; -- Bharara Rome Extradose (frasco) [p57]
update perfumes set precio_tienda_regular = 295, notas_olfativas = 'Aromático, Ámbar, Iris, Dulce, Amaderado', familia_olfativa = 'Aromático' where id = 240; -- Lattafa Pride Game Of Spades No Limit (frasco) [p63]
update perfumes set notas_olfativas = 'Afrutado, Floral, Aromático, Canela, Amaderado', familia_olfativa = 'Afrutado' where id = 253; -- Lattafa Rayhaan Aquatica (frasco) [p60]
update perfumes set precio_tienda_regular = 170, notas_olfativas = 'Dulce, Ámbar, Atalcado, Cítrico, Iris', inspirado_en = 'Le Beau Le Parfum de Jean Paul Gaultier', familia_olfativa = 'Dulce' where id = 255; -- Rasasi Hawas Malibu (frasco) [p23]
update perfumes set precio_tienda_regular = 170, notas_olfativas = 'Afrutados, Cítrico, Acuático, Fresco, Ámbar', inspirado_en = 'Invictus de Paco Rabanne', familia_olfativa = 'Afrutados' where id = 256; -- Rasasi Hawas (frasco) [p23]
update perfumes set precio_tienda_regular = 170, notas_olfativas = 'Fresco Especiado, Cítrico, Amaderado, Amizclado, Canela', inspirado_en = 'Imagination de Louis Vuitton', familia_olfativa = 'Fresco Especiado' where id = 257; -- Rasasi Hawas Kobra (frasco) [p24]
-- Mismo caso que id=77: esta fila tenía un descuento de consolidado propio (475/425), pero
-- bajar precio_tienda_regular a 400 sin tocar precio_consolidado_fijo lo dejaba por encima
-- (425 > 400) y violaba chk_precio_consolidado_menor. Se baja el consolidado al mismo 400
-- (pierde su margen propio por ahora) en vez de inventar un descuento -- ajustar con la
-- Calculadora de Márgenes si se quiere un precio de consolidado distinto al de tienda.
update perfumes set precio_tienda_regular = 400, precio_consolidado_fijo = 400, notas_olfativas = 'Cítrico, Aromático, Dulce, Bergamota, Amaderado', familia_olfativa = 'Cítrico' where id = 264; -- Valentino Uomo Born In Roma Intense (frasco) [p66]
update perfumes set precio_tienda_regular = 300, notas_olfativas = 'Afrutado, Floral, Aromático, Canela, Amaderado', familia_olfativa = 'Afrutado' where id = 270; -- King of Kings King Of Kings Nebula (frasco) [p58]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Avainillado, Atalcado, Amaderado, Coco, Afrutado', familia_olfativa = 'Avainillado' where id = 337; -- Lattafa Eclaire (decant) [p43]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Dulce, Avainillado, Cálido, Tropical, Atalcado', inspirado_en = 'Her Elixir de Burberry', familia_olfativa = 'Dulce' where id = 339; -- Lattafa Yara Pink (decant) [p35]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Tropical, Dulce, Avainillado, Floral, Atalcado', familia_olfativa = 'Tropical' where id = 341; -- Lattafa Yara Tous (decant) [p36]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Avainillados, Dulce, Afrutados, Atalcados, Floral', inspirado_en = 'Yum Pistachio Gelato 33 de Kayali', familia_olfativa = 'Avainillados' where id = 343; -- Lattafa Yara Candy (decant) [p35]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Dulce, Afrutado, Atalcado, Fresco, Amaderado', inspirado_en = 'Tribeca de Bond No. 9', familia_olfativa = 'Dulce' where id = 345; -- Lattafa Honor & Glory (decant) [p40]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Afrutados, Frescos Especiado, Rosas, Tropical, Dulce', inspirado_en = 'Eden Juicy Apple de Kayali', familia_olfativa = 'Afrutados' where id = 349; -- Lattafa Sublime (decant) [p40]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Avainillado, Ámbar, Cálido, Dulce, Aromático', inspirado_en = 'Ultra Male de Jean Paul Gaultier', familia_olfativa = 'Avainillado' where id = 351; -- Afnan 9PM (decant) [p8]
update perfumes set precio_3ml = 17, precio_5ml = 28, precio_10ml = 37, notas_olfativas = 'Cálido Especiado, Avainillado, Cálido, Ámbar, Amaderado', inspirado_en = 'Ultra Male Elixir de Jean Paul Gaultier', familia_olfativa = 'Cálido Especiado' where id = 353; -- Afnan 9PM Elixir (decant) [p8]
update perfumes set precio_3ml = 18, precio_5ml = 28, precio_10ml = 40, notas_olfativas = 'Cálido Especiado, Afrutado, Cálido, Dulce, Aromático', familia_olfativa = 'Cálido Especiado' where id = 355; -- Afnan 9PM Night Out (decant) [p9]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Afrutados, Cítrico, Floral, Fresco, Aromático', inspirado_en = 'Invictus Aqua de Paco Rabanne', familia_olfativa = 'Afrutados' where id = 357; -- Rasasi Hawas Ice (decant) [p22]
update perfumes set precio_3ml = 18, precio_5ml = 28, notas_olfativas = 'Avainillado, Aromático, Dulce, Ámbar, Amaderado', inspirado_en = 'Le Male Elixir de Jean Paul Gaultier', familia_olfativa = 'Avainillado' where id = 359; -- Rasasi Hawas Elixir (decant) [p22]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Cálido Especiado, Dulce, Avainillado, Café, Canela', familia_olfativa = 'Cálido Especiado' where id = 361; -- Lattafa Khamrah Qahwa (decant) [p31]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Aromático, Fresco, Amaderado, Rosas, Herbal', familia_olfativa = 'Aromático' where id = 363; -- Bharara Rome Pour Home (decant) [p56]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Cítrico, Aromático, Bergamota, Almizcado, Fresco', familia_olfativa = 'Cítrico' where id = 365; -- Bharara Rome Imagine (decant) [p56]
update perfumes set precio_3ml = 19, precio_5ml = 23, precio_10ml = 43, notas_olfativas = 'Afrutados, Dulce, Azónico, Atalcado, Avainillado', familia_olfativa = 'Afrutados' where id = 367; -- Bharara Bharara King (decant) [p53]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Ámbar, Frescos Especiado, Amaderado, Tabaco, Dulce', inspirado_en = 'Sauvage Elixir de Dior', familia_olfativa = 'Ámbar' where id = 369; -- Lattafa Asad (decant) [p38]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Avainillado, Cacao, Lavanda, Floral, Atalcado', inspirado_en = 'The Most Wanted Parfum de Azzaro', familia_olfativa = 'Avainillado' where id = 371; -- Lattafa Asad Bourbon (decant) [p37]
update perfumes set precio_3ml = 18, precio_5ml = 28, precio_10ml = 40, notas_olfativas = 'Cítrico, Dulce, Caramelo, Ámbar', inspirado_en = 'Scandal Pour Homme Le Parfum de Jean Paul Gaultier', familia_olfativa = 'Cítrico' where id = 373; -- Armaf Odyssey Mandarin Sky Elixir (decant) [p12]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Aromático, Fresco Especiado, Cítrico, Ámbar, Amaderado', inspirado_en = 'Invictus Platinum de Paco Rabanne', familia_olfativa = 'Aromático' where id = 375; -- Armaf Odyssey Aqua (decant) [p11]
update perfumes set precio_3ml = 15, precio_10ml = 35, notas_olfativas = 'Cítrico, Aromático, Caramelo, Avainillado, Ámbar', inspirado_en = 'Scandal Pour Homme de Jean Paul Gaultier', familia_olfativa = 'Cítrico' where id = 377; -- Armaf Odyssey Mandarin Sky (decant) [p12]
update perfumes set precio_3ml = 20, notas_olfativas = 'Aromático, Ámbar, Iris, Dulce, Amaderado', familia_olfativa = 'Aromático' where id = 379; -- Lattafa Pride Game Of Spades No Limit (decant) [p63]
update perfumes set precio_5ml = 40, notas_olfativas = 'Fresco, Mineral, Acuático, Azónico, Amaderado', familia_olfativa = 'Fresco' where id = 394; -- Jean Paul Gaultier Le Beau Le Parfum Intense (decant) [p69]
update perfumes set precio_5ml = 40, notas_olfativas = 'Avainillado, Dulce, Aromático, Amielado, Ámbar', familia_olfativa = 'Avainillado' where id = 396; -- Jean Paul Gaultier Le Male Elixir (decant) [p68]
update perfumes set precio_5ml = 40, notas_olfativas = 'Fresco, Mineral, Acuático, Azónico, Amaderado', familia_olfativa = 'Fresco' where id = 399; -- Valentino Uomo Born In Roma (decant) [p67]
update perfumes set precio_5ml = 40, notas_olfativas = 'Lavanda, Cálido, Aromático, Ámbar, Amaderado', familia_olfativa = 'Lavanda' where id = 403; -- Valentino Uomo Born In Roma Extradosis (decant) [p66]

/* ================================================================
   2. PRODUCTOS NUEVOS -- frascos completos que no tenian ninguna fila
   ================================================================ */

insert into perfumes (slug, nombre, marca, genero, concentracion, mililitros, descripcion, notas_olfativas, inspirado_en, familia_olfativa, precio_tienda_regular, precio_consolidado_fijo, margen_aplicado, tipo_casa, es_decant, activo, estado)
values
  ('armaf-odyssey-mfga', 'Odyssey Mfga', 'Armaf', 'Unisex', 'Eau de Parfum', 100, null, 'Cítrico, Aromático, Dulce, Bergamota, Amaderado', 'Y Eau de Parfum de Yves Saint Laurent', 'Cítrico', 150, 150, true, 'Árabe', false, true, 'Disponible'), -- p13 [exact YSL ref ambiguous]
  ('lattafa-qaed-ultimati', 'Qaed Ultimati', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, null, 'Atalcado, Afrutado, Avainillado, Coco, Dulce', null, 'Atalcado', 140, 140, true, 'Árabe', false, true, 'Disponible'), -- p19 [bottle photo mislabeled reused from Qaed Al Fursan]
  ('rasasi-hawas-sapphire', 'Hawas Sapphire', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, null, 'Afrutados, Cítrico, Floral, Amaderados, Tropical', null, 'Afrutados', 185, 185, true, 'Árabe', false, true, 'Disponible'), -- p26 ['FBFragrances Edition' printed on bottle]
  ('rasasi-hawas-lava-gold', 'Hawas Lava Gold', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, null, 'Cuero, Afrutados, Cálido Especiado, Terrazo, Ámbar', null, 'Cuero', 185, 185, true, 'Árabe', false, true, 'Disponible'), -- p27
  ('rasasi-hawas-verde', 'Hawas Verde', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, null, 'Cítrico, Aromático, Fresco, Amaderado, Atalcado', 'Torino 21 de Xerjoff', 'Cítrico', 195, 195, true, 'Árabe', false, true, 'Disponible'), -- p27
  ('rasasi-hawas-london', 'Hawas London', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, null, 'Ámbar, Rosas, Almizcados, Cálido, Floral', 'Donna Born In Roma Intense de Valentino', 'Ámbar', 185, 185, true, 'Árabe', false, true, 'Disponible'), -- p28 [DUP repeated from Hawas Diva, likely copy-paste error]
  ('rasasi-hawas-chrome', 'Hawas Chrome', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, null, 'Afrutados, Dulce, Tropical, Acuático, Atalcado', 'Erba Gold de Xerjoff', 'Afrutados', 185, 185, true, 'Árabe', false, true, 'Disponible'), -- p28
  ('rasasi-hawas-pink', 'Hawas Pink', 'Rasasi', 'Mujer', 'Eau de Parfum', 100, null, 'Ámbar, Rosas, Almizcados, Cálido, Floral', null, 'Ámbar', 185, 185, true, 'Árabe', false, true, 'Disponible'), -- p29
  ('rasasi-hawas-viper', 'Hawas Viper', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, null, 'Tabaco, Aromático, Cálido, Dulce, Atalcado', null, 'Tabaco', 185, 185, true, 'Árabe', false, true, 'Disponible'), -- p29
  ('lattafa-yara-pink', 'Yara Pink', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, null, 'Dulce, Avainillado, Cálido, Tropical, Atalcado', 'Her Elixir de Burberry', 'Dulce', 150, 150, true, 'Árabe', false, true, 'Disponible'), -- p35
  ('lattafa-hayaati-florence', 'Hayaati Florence', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, null, 'Cítrico, Fresco, Amizclado, Dulce, Afrutado', null, 'Cítrico', 165, 165, true, 'Árabe', false, true, 'Disponible'), -- p45
  ('armaf-dunascape-dubai', 'Dunascape Dubai', 'Armaf', 'Unisex', 'Eau de Parfum', 100, null, 'Cítrico, Aromático, Amaderado, Almizcado, Fresco', null, 'Cítrico', 190, 190, true, 'Árabe', false, true, 'Disponible'), -- p49 [bottle print reads 'PHNESCAPE']
  ('rasasi-nitro-white', 'Nitro White', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, null, 'Amielado, Avainillado, Ámbar, Atalcado, Aromático', null, 'Amielado', 185, 185, true, 'Árabe', false, true, 'Disponible'), -- p49 [brand low confidence]
  ('al-haramain-haramain-aqua-dubai', 'Haramain Aqua Dubai', 'Al Haramain', 'Unisex', 'Extrait de Parfum', 120, null, 'Cítrico, Ámbar, Verde, Afrutados, Amizclados', null, 'Cítrico', 235, 235, true, 'Árabe', false, true, 'Disponible'), -- p51 [SOLD OUT on page]
  ('bharara-pharaoh-ramesses-ii', 'Pharaoh Ramesses II', 'Bharara', 'Hombre', 'Eau de Parfum', 100, null, 'Cálido Especiado, Pachulí, Cuero, Cacao, Canela', null, 'Cálido Especiado', 400, 400, true, 'Árabe', false, true, 'Disponible'), -- p54
  ('bharara-rome-imagine', 'Rome Imagine', 'Bharara', 'Unisex', 'Eau de Parfum', 100, null, 'Cítrico, Aromático, Bergamota, Almizcado, Fresco', null, 'Cítrico', 160, 160, true, 'Árabe', false, true, 'Disponible'), -- p56 [brand low confidence]
  ('bharara-rome-paradox', 'Rome Paradox', 'Bharara', 'Unisex', 'Eau de Parfum', 100, null, 'Bergamota, Floral, Aromático, Cítrico, Dulce', null, 'Bergamota', 160, 160, true, 'Árabe', false, true, 'Disponible'), -- p57 [brand low confidence]
  ('por-definir-uomo-intense', 'Uomo Intense', 'Por Definir', 'Unisex', 'Eau de Parfum', 100, null, 'Dulce, Afrutado, Avainillado, Lavanda, Ámbar', null, 'Dulce', 160, 160, true, 'Árabe', false, true, 'Disponible'), -- p58 [brand low confidence]
  ('lattafa-rayhaan-wolf', 'Rayhaan Wolf', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, null, 'Cálido Especiado, Ámbar, Leñoso, Dulce, Amaderado', null, 'Cálido Especiado', 200, 200, true, 'Árabe', false, true, 'Disponible'), -- p61 [brand/spelling low confidence]
  ('lattafa-pride-game-of-spades-bio', 'Game Of Spades Bio', 'Lattafa Pride', 'Hombre', 'Eau de Parfum', 100, null, 'Fresco, Cítrico, Floral, Cálido, Amaderado', null, 'Fresco', 250, 250, true, 'Árabe', false, true, 'Disponible'), -- p64 [header/bottle/marketing-page names disagree (Bi Parfum/BID/Bio)]
  ('lattafa-pride-game-of-spades-double-bonus', 'Game Of Spades Double Bonus', 'Lattafa Pride', 'Hombre', 'Eau de Parfum', 100, null, 'Ámbar, Avainillado, Dulce, Floral, Afrutado', null, 'Ámbar', 295, 295, true, 'Árabe', false, true, 'Disponible'), -- p64 [SOLD OUT on page]
  ('valentino-uomo-born-in-roma', 'Uomo Born In Roma', 'Valentino', 'Hombre', 'Eau de Toilette', 100, null, 'Fresco, Mineral, Acuático, Azónico, Amaderado', null, 'Fresco', 480, 480, true, 'Diseñador', false, true, 'Disponible'), -- p67
  ('valentino-born-in-roma', 'Born In Roma', 'Valentino', 'Mujer', 'Eau de Parfum', 100, null, 'Cítrico, Dulce, Caramelo, Ámbar, Amaderado', null, 'Cítrico', 480, 480, true, 'Diseñador', false, true, 'Disponible'), -- p67 [SOLD OUT on page]
  ('jean-paul-gaultier-le-male', 'Le Male', 'Jean Paul Gaultier', 'Hombre', 'Eau de Toilette', 100, null, 'Avainillado, Fresco, Aromático, Lavanda, Cálido', null, 'Avainillado', 400, 400, true, 'Diseñador', false, true, 'Disponible'), -- p69 [SOLD OUT on page]
  ('yves-saint-laurent-y-eau-de-parfum', 'Y Eau De Parfum', 'Yves Saint Laurent', 'Hombre', 'Eau de Parfum', 100, null, 'Aromático, Amaderado, Acuático, Fresco, Cálido', null, 'Aromático', 500, 500, true, 'Diseñador', false, true, 'Disponible'), -- p70 [SOLD OUT on page; exact YSL product name low confidence]
  ('yves-saint-laurent-y-le-parfum', 'Y Le Parfum', 'Yves Saint Laurent', 'Hombre', 'Parfum', 100, null, 'Avainillado, Fresco, Aromático, Lavanda, Cálido', null, 'Avainillado', 400, 400, true, 'Diseñador', false, true, 'Disponible'), -- p70 [exact YSL product name low confidence]
  ('dolce-gabbana-light-blue-pour-homme', 'Light Blue Pour Homme', 'Dolce & Gabbana', 'Hombre', 'Eau de Toilette', 100, null, 'Cítrico, Fresco, Amaderado, Pachulí, Cálido', null, 'Cítrico', 320, 320, true, 'Diseñador', false, true, 'Disponible'); -- p71 [SOLD OUT on page]


/* ================================================================
   3. PRODUCTOS NUEVOS -- decants que no tenian ninguna fila
   ================================================================ */

insert into perfumes (slug, nombre, marca, genero, concentracion, mililitros, descripcion, notas_olfativas, inspirado_en, familia_olfativa, precio_3ml, precio_5ml, precio_10ml, precio_tienda_regular, precio_consolidado_fijo, margen_aplicado, tipo_casa, es_decant, activo, estado)
values
  ('afnan-9am-dive-decant', '9AM Dive', 'Afnan', 'Unisex', 'Eau de Parfum', 100, 'Decant de 9AM Dive (Afnan), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutado, Cítrico, Verde, Ámbar, Amaderado', 'Y Eau de Parfum de Yves Saint Laurent', 'Afrutado', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p9 [DUP ambiguous exact YSL ref]
  ('armaf-odyssey-spectra-decant', 'Odyssey Spectra', 'Armaf', 'Unisex', 'Eau de Parfum', 100, 'Decant de Odyssey Spectra (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Canela, Avainillado, Tabaco, Dulce, Aromático', 'Ultra Male de Jean Paul Gaultier', 'Canela', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p11
  ('armaf-odyssey-mfga-decant', 'Odyssey Mfga', 'Armaf', 'Unisex', 'Eau de Parfum', 100, 'Decant de Odyssey Mfga (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Aromático, Dulce, Bergamota, Amaderado', 'Y Eau de Parfum de Yves Saint Laurent', 'Cítrico', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p13 [exact YSL ref ambiguous]
  ('armaf-odyssey-limoni-decant', 'Odyssey Limoni', 'Armaf', 'Unisex', 'Eau de Parfum', 100, 'Decant de Odyssey Limoni (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Dulce, Caramelo, Ámbar, Amaderado', 'Afternoon Swim de Louis Vuitton', 'Cítrico', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p13
  ('armaf-odyssey-coffee-toffee-decant', 'Odyssey Coffee Toffee', 'Armaf', 'Unisex', 'Eau de Parfum', 100, 'Decant de Odyssey Coffee Toffee (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Café, Cacao, Dulce, Amielado, Avainillado', null, 'Café', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p14
  ('armaf-odyssey-artisto-decant', 'Odyssey Artisto', 'Armaf', 'Unisex', 'Eau de Parfum', 100, 'Decant de Odyssey Artisto (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Avainillado, Ámbar, Coco, Tropical, Dulce', 'Le Beau Eau de Toilette de Jean Paul Gaultier', 'Avainillado', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p14 [5th pill partly obscured]
  ('armaf-club-de-nuit-urban-man-elixir-decant', 'Club De Nuit Urban Man Elixir', 'Armaf', 'Hombre', 'Eau de Parfum', 100, 'Decant de Club De Nuit Urban Man Elixir (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Ámbar, Aromático, Frescos, Cítrico, Almizcado', 'Sauvage de Dior', 'Ámbar', 17, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p16
  ('armaf-club-de-nuit-intense-man-decant', 'Club De Nuit Intense Man', 'Armaf', 'Hombre', 'Eau de Parfum', 100, 'Decant de Club De Nuit Intense Man (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Afrutado, Amaderado, Cuero, Dulce', 'Aventus de Creed', 'Cítrico', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p16
  ('armaf-club-de-nuit-maleka-decant', 'Club De Nuit Maleka', 'Armaf', 'Mujer', 'Eau de Parfum', 100, 'Decant de Club De Nuit Maleka (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutados, Aromático, Frescos, Cítrico, Vainilla', null, 'Afrutados', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p17
  ('armaf-club-de-nuit-iconic-decant', 'Club De Nuit Iconic', 'Armaf', 'Hombre', 'Eau de Parfum', 100, 'Decant de Club De Nuit Iconic (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Cálido, Aromático, Ámbar, Dulce', 'Bleu de Chanel Eau de Parfum', 'Cítrico', 18, 28, 38, 38, 38, true, 'Árabe', true, true, 'Disponible'), -- p17
  ('lattafa-qaed-al-fursan-decant', 'Qaed Al Fursan', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, 'Decant de Qaed Al Fursan (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutados, Dulces, Frescos, Cítrico, Amaderados', null, 'Afrutados', 14, 23, 30, 30, 30, true, 'Árabe', true, true, 'Disponible'), -- p19
  ('lattafa-qaed-ultimati-decant', 'Qaed Ultimati', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, 'Decant de Qaed Ultimati (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Atalcado, Afrutado, Avainillado, Coco, Dulce', null, 'Atalcado', 14, 23, 30, 30, 30, true, 'Árabe', true, true, 'Disponible'), -- p19 [bottle photo mislabeled reused from Qaed Al Fursan]
  ('lattafa-qaed-untamed-decant', 'Qaed Untamed', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, 'Decant de Qaed Untamed (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Aromático, Ámbar, Frescos, Caramelo, Amaderados', 'Eros de Versace', 'Aromático', 13, 24, 30, 30, 30, true, 'Árabe', true, true, 'Disponible'), -- p20 [DUP text said 'Versace Eros Najim']
  ('por-definir-tubbes-candy-apple-decant', 'Tubbes Candy Apple', 'Por Definir', 'Unisex', 'Eau de Parfum', 100, 'Decant de Tubbes Candy Apple (Por Definir), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Atalcado, Afrutado, Avainillado, Coco, Dulce', null, 'Atalcado', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p20 [brand very low confidence, novelty bottle, no frasco price shown]
  ('rasasi-hawas-decant', 'Hawas', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutados, Cítrico, Acuático, Fresco, Ámbar', 'Invictus de Paco Rabanne', 'Afrutados', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p23
  ('rasasi-hawas-malibu-decant', 'Hawas Malibu', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Malibu (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Dulce, Ámbar, Atalcado, Cítrico, Iris', 'Le Beau Le Parfum de Jean Paul Gaultier', 'Dulce', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p23
  ('rasasi-hawas-kobra-decant', 'Hawas Kobra', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Kobra (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Fresco Especiado, Cítrico, Amaderado, Amizclado, Canela', 'Imagination de Louis Vuitton', 'Fresco Especiado', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p24
  ('rasasi-hawas-tropical-decant', 'Hawas Tropical', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Tropical (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Dulce, Coco, Amaderado, Verde, Avainillado', 'Le Beau Paradise Garden de Jean Paul Gaultier', 'Dulce', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p24
  ('rasasi-hawas-black-decant', 'Hawas Black', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Black (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Amaderado, Cítrico, Musgosos, Tarrosos, Afrutados', 'Hacivat de Nishane', 'Amaderado', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p25
  ('rasasi-hawas-diva-decant', 'Hawas Diva', 'Rasasi', 'Mujer', 'Eau de Parfum', 100, 'Decant de Hawas Diva (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Avainillado, Afrutados, Ámbar, Atalcado, Amaderado', 'Donna Born In Roma Intense de Valentino', 'Avainillado', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p26
  ('rasasi-hawas-sapphire-decant', 'Hawas Sapphire', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Sapphire (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutados, Cítrico, Floral, Amaderados, Tropical', null, 'Afrutados', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p26 ['FBFragrances Edition' printed on bottle]
  ('rasasi-hawas-lava-gold-decant', 'Hawas Lava Gold', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Lava Gold (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cuero, Afrutados, Cálido Especiado, Terrazo, Ámbar', null, 'Cuero', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p27
  ('rasasi-hawas-verde-decant', 'Hawas Verde', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Verde (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Aromático, Fresco, Amaderado, Atalcado', 'Torino 21 de Xerjoff', 'Cítrico', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p27
  ('rasasi-hawas-london-decant', 'Hawas London', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas London (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Ámbar, Rosas, Almizcados, Cálido, Floral', 'Donna Born In Roma Intense de Valentino', 'Ámbar', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p28 [DUP repeated from Hawas Diva, likely copy-paste error]
  ('rasasi-hawas-chrome-decant', 'Hawas Chrome', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Chrome (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutados, Dulce, Tropical, Acuático, Atalcado', 'Erba Gold de Xerjoff', 'Afrutados', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p28
  ('rasasi-hawas-pink-decant', 'Hawas Pink', 'Rasasi', 'Mujer', 'Eau de Parfum', 100, 'Decant de Hawas Pink (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Ámbar, Rosas, Almizcados, Cálido, Floral', null, 'Ámbar', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p29
  ('rasasi-hawas-viper-decant', 'Hawas Viper', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Hawas Viper (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Tabaco, Aromático, Cálido, Dulce, Atalcado', null, 'Tabaco', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p29
  ('lattafa-khamrah-decant', 'Khamrah', 'Lattafa', 'Unisex', 'Eau de Parfum', 100, 'Decant de Khamrah (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Dulce, Cálido Especiado, Ámbar, Canela, Amaderado', 'Angels'' Share de By Kilian', 'Dulce', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p31
  ('lattafa-khamrah-dukhan-decant', 'Khamrah Dukhan', 'Lattafa', 'Unisex', 'Eau de Parfum', 100, 'Decant de Khamrah Dukhan (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Ámbar, Cálido Especiado, Dulce, Tabaco, Amaderado', null, 'Ámbar', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p32
  ('lattafa-khamrah-waha-decant', 'Khamrah Waha', 'Lattafa', 'Unisex', 'Eau de Parfum', 100, 'Decant de Khamrah Waha (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Fresco Picante, Aromático, Agrios, Vainilla, Leñoso', null, 'Fresco Picante', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p32
  ('lattafa-yara-elixir-decant', 'Yara Elixir', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Yara Elixir (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Avainillados, Caramelo, Afrutados, Atalcados, Floral', null, 'Avainillados', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p36
  ('lattafa-yara-moi-decant', 'Yara Moi', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Yara Moi (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Amaderado, Pachulí, Caramelo, Cálido, Floral', null, 'Amaderado', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p37
  ('lattafa-asad-elixir-decant', 'Asad Elixir', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, 'Decant de Asad Elixir (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Ámbar, Avainillado, Amaderado, Fresco, Atalcado', null, 'Ámbar', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p38
  ('lattafa-noble-blush-decant', 'Noble Blush', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Noble Blush (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Dulce, Atalcado, Fresco, Almendrado, Afrutado', 'Good Girl Blush Elixir de Carolina Herrera', 'Dulce', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p41
  ('lattafa-amethyst-decant', 'Amethyst', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Amethyst (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Rosas, Oud, Ámbar, Florales, Avainillado', null, 'Rosas', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p41
  ('lattafa-oud-for-glory-decant', 'Oud For Glory', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, 'Decant de Oud For Glory (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cálido Especiado, Pachulí, Fresco, Amaderado, Metálico', null, 'Cálido Especiado', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p42
  ('lattafa-the-kingdom-decant', 'The Kingdom', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, 'Decant de The Kingdom (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Aromático, Dulce, Ámbar, Lavanda, Avainillado', null, 'Aromático', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p42
  ('lattafa-eclaire-pistacho-decant', 'Eclaire Pistacho', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Eclaire Pistacho (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Lactónico, Coco, Cacao, Dulce, Avainillado', null, 'Lactónico', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p43
  ('lattafa-fakhar-rose-decant', 'Fakhar Rose', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Fakhar Rose (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Floral Blanco, Nardos, Amaderado, Dulce, Afrutado', null, 'Floral Blanco', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p44
  ('lattafa-haya-decant', 'Haya', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Haya (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Floral, Cítrico, Afrutado, Dulce, Avainillado', null, 'Floral', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p44 [brand low confidence]
  ('lattafa-hayaati-florence-decant', 'Hayaati Florence', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Hayaati Florence (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Fresco, Amizclado, Dulce, Afrutado', null, 'Cítrico', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p45
  ('lattafa-hayaati-decant', 'Hayaati', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Hayaati (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutados, Canela, Almizcado, Cálido, Atalcado', null, 'Afrutados', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p45
  ('lattafa-nebras-elixir-decant', 'Nebras Elixir', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Nebras Elixir (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Avainillado, Atalcado, Amizclado, Dulce, Ámbar', null, 'Avainillado', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p47
  ('lattafa-nebras-decant', 'Nebras', 'Lattafa', 'Mujer', 'Eau de Parfum', 100, 'Decant de Nebras (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Avainillado, Atalcado, Dulce, Frutales, Almizcado', null, 'Avainillado', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p47 [SOLD OUT on page]
  ('lattafa-pride-art-of-universe-decant', 'Art Of Universe', 'Lattafa Pride', 'Unisex', 'Eau de Parfum', 100, 'Decant de Art Of Universe (Lattafa Pride), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Afrutado, Verde, Dulce, Floral', null, 'Cítrico', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p48
  ('lattafa-pride-pisa-decant', 'Pisa', 'Lattafa Pride', 'Unisex', 'Eau de Parfum', 100, 'Decant de Pisa (Lattafa Pride), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Atalcado, Dulce, Amaderado, Almizcado', null, 'Cítrico', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p48 [brand low confidence]
  ('armaf-dunascape-dubai-decant', 'Dunascape Dubai', 'Armaf', 'Unisex', 'Eau de Parfum', 100, 'Decant de Dunascape Dubai (Armaf), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Aromático, Amaderado, Almizcado, Fresco', null, 'Cítrico', 18, 28, 40, 40, 40, true, 'Árabe', true, true, 'Disponible'), -- p49 [bottle print reads 'PHNESCAPE']
  ('rasasi-nitro-white-decant', 'Nitro White', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de Nitro White (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Amielado, Avainillado, Ámbar, Atalcado, Aromático', null, 'Amielado', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p49 [brand low confidence]
  ('al-haramain-haramain-amber-oud-decant', 'Haramain Amber Oud', 'Al Haramain', 'Unisex', 'Extrait de Parfum', 100, 'Decant de Haramain Amber Oud (Al Haramain), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutados, Dulce, Ozónico, Atalcado, Avainillado', 'Erba Pura de Xerjoff', 'Afrutados', 19, 23, 43, 43, 43, true, 'Árabe', true, true, 'Disponible'), -- p51
  ('al-haramain-haramain-aqua-dubai-decant', 'Haramain Aqua Dubai', 'Al Haramain', 'Unisex', 'Extrait de Parfum', 100, 'Decant de Haramain Aqua Dubai (Al Haramain), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Ámbar, Verde, Afrutados, Amizclados', null, 'Cítrico', 19, 23, 43, 43, 43, true, 'Árabe', true, true, 'Disponible'), -- p51 [SOLD OUT on page]
  ('bharara-pharaoh-ramesses-decant', 'Pharaoh Ramesses', 'Bharara', 'Hombre', 'Eau de Parfum', 100, 'Decant de Pharaoh Ramesses (Bharara), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cálido Especiado, Amaderado, Dulce, Afrutados, Avainillado', null, 'Cálido Especiado', 20, 40, 60, 60, 60, true, 'Árabe', true, true, 'Disponible'), -- p53
  ('bharara-pharaoh-ramesses-ii-decant', 'Pharaoh Ramesses II', 'Bharara', 'Hombre', 'Eau de Parfum', 100, 'Decant de Pharaoh Ramesses II (Bharara), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cálido Especiado, Pachulí, Cuero, Cacao, Canela', null, 'Cálido Especiado', 20, 40, 60, 60, 60, true, 'Árabe', true, true, 'Disponible'), -- p54
  ('bharara-rome-paradox-decant', 'Rome Paradox', 'Bharara', 'Unisex', 'Eau de Parfum', 100, 'Decant de Rome Paradox (Bharara), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Bergamota, Floral, Aromático, Cítrico, Dulce', null, 'Bergamota', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p57 [brand low confidence]
  ('bharara-rome-extradose-decant', 'Rome Extradose', 'Bharara', 'Unisex', 'Eau de Parfum', 100, 'Decant de Rome Extradose (Bharara), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Lavanda, Cálido, Amaderado, Aromático, Frescos', null, 'Lavanda', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p57 [brand low confidence]
  ('king-of-kings-king-of-kings-nebula-decant', 'King Of Kings Nebula', 'King of Kings', 'Hombre', 'Extrait de Parfum', 100, 'Decant de King Of Kings Nebula (King of Kings), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutado, Floral, Aromático, Canela, Amaderado', null, 'Afrutado', 20, 40, 60, 60, 60, true, 'Árabe', true, true, 'Disponible'), -- p58 [brand guess, real brand is 'King of Kings' per live catalog]
  ('por-definir-uomo-intense-decant', 'Uomo Intense', 'Por Definir', 'Unisex', 'Eau de Parfum', 100, 'Decant de Uomo Intense (Por Definir), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Dulce, Afrutado, Avainillado, Lavanda, Ámbar', null, 'Dulce', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p58 [brand low confidence]
  ('lattafa-rayhaan-aquatica-decant', 'Rayhaan Aquatica', 'Lattafa', 'Unisex', 'Eau de Parfum', 100, 'Decant de Rayhaan Aquatica (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Afrutado, Floral, Aromático, Canela, Amaderado', null, 'Afrutado', 19, 23, 43, 43, 43, true, 'Árabe', true, true, 'Disponible'), -- p60 [brand/spelling low confidence Rayhaam/Rayhaan]
  ('lattafa-rayhaan-tropical-vibe-decant', 'Rayhaan Tropical Vibe', 'Lattafa', 'Unisex', 'Eau de Parfum', 100, 'Decant de Rayhaan Tropical Vibe (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Tropical, Afrutado, Dulce, Cítrico, Coco', null, 'Tropical', 19, 23, 43, 43, 43, true, 'Árabe', true, true, 'Disponible'), -- p60 [brand/spelling low confidence]
  ('lattafa-rayhaan-wolf-decant', 'Rayhaan Wolf', 'Lattafa', 'Hombre', 'Eau de Parfum', 100, 'Decant de Rayhaan Wolf (Lattafa), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cálido Especiado, Ámbar, Leñoso, Dulce, Amaderado', null, 'Cálido Especiado', 19, 23, 43, 43, 43, true, 'Árabe', true, true, 'Disponible'), -- p61 [brand/spelling low confidence]
  ('rasasi-his-confession-decant', 'His Confession', 'Rasasi', 'Hombre', 'Eau de Parfum', 100, 'Decant de His Confession (Rasasi), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Tropical, Afrutado, Dulce, Cítrico, Coco', null, 'Tropical', 15, 25, 35, 35, 35, true, 'Árabe', true, true, 'Disponible'), -- p61
  ('lattafa-pride-game-of-spades-wildcard-decant', 'Game Of Spades Wildcard', 'Lattafa Pride', 'Hombre', 'Eau de Parfum', 100, 'Decant de Game Of Spades Wildcard (Lattafa Pride), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Ámbar, Avainillado, Dulce, Floral, Afrutado', null, 'Ámbar', 20, 40, 60, 60, 60, true, 'Árabe', true, true, 'Disponible'), -- p63 [SOLD OUT on page]
  ('lattafa-pride-game-of-spades-bio-decant', 'Game Of Spades Bio', 'Lattafa Pride', 'Hombre', 'Eau de Parfum', 100, 'Decant de Game Of Spades Bio (Lattafa Pride), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Fresco, Cítrico, Floral, Cálido, Amaderado', null, 'Fresco', 20, 40, 60, 60, 60, true, 'Árabe', true, true, 'Disponible'), -- p64 [header/bottle/marketing-page names disagree (Bi Parfum/BID/Bio)]
  ('lattafa-pride-game-of-spades-double-bonus-decant', 'Game Of Spades Double Bonus', 'Lattafa Pride', 'Hombre', 'Eau de Parfum', 100, 'Decant de Game Of Spades Double Bonus (Lattafa Pride), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Ámbar, Avainillado, Dulce, Floral, Afrutado', null, 'Ámbar', 20, 40, 60, 60, 60, true, 'Árabe', true, true, 'Disponible'), -- p64 [SOLD OUT on page]
  ('valentino-uomo-born-in-roma-intense-decant', 'Uomo Born In Roma Intense', 'Valentino', 'Hombre', 'Eau de Parfum', 100, 'Decant de Uomo Born In Roma Intense (Valentino), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Aromático, Dulce, Bergamota, Amaderado', null, 'Cítrico', 20, 40, 60, 60, 60, true, 'Diseñador', true, true, 'Disponible'), -- p66
  ('valentino-born-in-roma-decant', 'Born In Roma', 'Valentino', 'Mujer', 'Eau de Parfum', 100, 'Decant de Born In Roma (Valentino), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Dulce, Caramelo, Ámbar, Amaderado', null, 'Cítrico', 20, 40, 60, 60, 60, true, 'Diseñador', true, true, 'Disponible'), -- p67 [SOLD OUT on page]
  ('jean-paul-gaultier-le-male-decant', 'Le Male', 'Jean Paul Gaultier', 'Hombre', 'Eau de Toilette', 100, 'Decant de Le Male (Jean Paul Gaultier), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Avainillado, Fresco, Aromático, Lavanda, Cálido', null, 'Avainillado', 20, 40, 60, 60, 60, true, 'Diseñador', true, true, 'Disponible'), -- p69 [SOLD OUT on page]
  ('yves-saint-laurent-y-eau-de-parfum-decant', 'Y Eau De Parfum', 'Yves Saint Laurent', 'Hombre', 'Eau de Parfum', 100, 'Decant de Y Eau De Parfum (Yves Saint Laurent), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Aromático, Amaderado, Acuático, Fresco, Cálido', null, 'Aromático', 20, 40, 60, 60, 60, true, 'Diseñador', true, true, 'Disponible'), -- p70 [SOLD OUT on page; exact YSL product name low confidence]
  ('yves-saint-laurent-y-le-parfum-decant', 'Y Le Parfum', 'Yves Saint Laurent', 'Hombre', 'Parfum', 100, 'Decant de Y Le Parfum (Yves Saint Laurent), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Avainillado, Fresco, Aromático, Lavanda, Cálido', null, 'Avainillado', 20, 40, 60, 60, 60, true, 'Diseñador', true, true, 'Disponible'), -- p70 [exact YSL product name low confidence]
  ('dolce-gabbana-light-blue-decant', 'Light Blue', 'Dolce & Gabbana', 'Mujer', 'Eau de Toilette', 100, 'Decant de Light Blue (Dolce & Gabbana), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Afrutado, Fresco, Fresco Acuático, Cálido', null, 'Cítrico', 20, 40, 60, 60, 60, true, 'Diseñador', true, true, 'Disponible'), -- p71 [4th pill low confidence, page showed duplicate 'Fresco']
  ('dolce-gabbana-light-blue-pour-homme-decant', 'Light Blue Pour Homme', 'Dolce & Gabbana', 'Hombre', 'Eau de Toilette', 100, 'Decant de Light Blue Pour Homme (Dolce & Gabbana), fraccionado del frasco original — 100% original, ideal para probar antes de llevar el frasco completo.', 'Cítrico, Fresco, Amaderado, Pachulí, Cálido', null, 'Cítrico', 20, 40, 60, 60, 60, true, 'Diseñador', true, true, 'Disponible'); -- p71 [SOLD OUT on page]
