-- ==========================================================
-- OCULTAR CATALOGO FUERA DEL EXCEL VIP VIGENTE (17 ago 2026)
--
-- Fuente: 'CONSOLIDADO VIP _ZADACA (1).xlsx' (198 filas, 196 nombres unicos).
-- El catalogo tenia 327 productos porque, ademas de lo que ya se cruzo
-- contra este Excel en actualizar_catalogo_vip_agosto.sql y
-- actualizar_catalogo_vip_15ago.sql (200 productos hoy en dia: 82
-- actualizados de la ronda original + 118 nuevos insertados desde el Excel,
-- menos 2 duplicados ya borrados en correccion_marca_y_duplicados.sql),
-- seguian activos los 127 productos de la carga inicial
-- (seed del 5 de agosto) que NUNCA se cruzaron contra este Excel: testers,
-- variantes con nombre mal escrito ("Odisey Aqua", "Roma Wome Bahara"),
-- filas con marca "Por Definir" sin identificar, y lineas/tamanos que
-- Maison Zadaca ya no maneja en esta campana VIP.
--
-- En vez de borrarlos (lo que fallaria para cualquiera que ya tenga un
-- pedido o reserva real, y borraria en cascada sus resenas/favoritos/
-- carritos), se marcan como activo = false -- requiere haber corrido antes
-- la migracion supabase/migrations/0008_activo_catalogo.sql. Quedan fuera
-- del catalogo de tienda, de consolidado y del buscador, pero el admin los
-- sigue viendo en el panel (Productos) y puede reactivarlos ahi mismo si
-- alguno si se sigue vendiendo.
--
-- Ejecutar en el SQL Editor de Supabase, DESPUES de la migracion 0008.
-- ==========================================================

update perfumes set activo = false where slug in (
    'afnan-9pm-tester-100ml', -- 9PM Tester. (Afnan)
    'afnan-afnan-9am-dive-3pcsset-u-3-4-edp-vaporizador-5-0-s-gel-5-0-deo-100ml', -- Afnan 9AM Dive 3pcsset U 3.4 EDP Vaporizador / 5.0 S.gel / 5.0 DEO (Afnan)
    'afnan-set-9pm-pour-homme-afnan-100ml', -- Set 9PM Pour Homme Afnan (Afnan)
    'afnan-tester-white-box-9-am-dive-100ml', -- Tester White Box 9 Am Dive (Afnan)
    'afnan-turathi-blue-afnan-for-men-100ml', -- Turathi Blue Afnan For Men (Afnan)
    'afnan-turathi-electric-afnan-for-women-and-men-100ml', -- Turathi Electric Afnan For Women And Men (Afnan)
    'al-haramain-al-haramain-amber-oud-dubai-night-unisex-extraido-de-parfum-75ml', -- AL Haramain Amber OUD Dubai Night Unisex Extraido DE Parfum (Al Haramain)
    'al-haramain-al-haramain-amber-oud-exclusif-emeral-100ml', -- Al Haramain Amber Oud Exclusif Emeral (Al Haramain)
    'al-haramain-al-haramain-gold-edition-200ml', -- Al Haramain Gold Edition (Al Haramain)
    'al-haramain-amber-gold-100ml', -- Amber Gold (Al Haramain)
    'al-haramain-amber-oud-gold-200ml', -- Amber OUD Gold (Al Haramain)
    'armaf-armaf-club-de-nuit-precieux-iv-100ml', -- Armaf Club DE Nuit Precieux IV (Armaf)
    'armaf-armaf-odyssey-go-mango-100ml', -- Armaf Odyssey GO Mango (Armaf)
    'armaf-cdn-intense-edp-200ml', -- CDN Intense EDP (Armaf)
    'armaf-check-mate-king-edp-men-by-armaf-100ml', -- Check Mate King EDP MEN - BY Armaf (Armaf)
    'por-definir-chect-mate-king-mujer-100ml', -- Checkmate Queen (Armaf)
    'armaf-club-de-nuit-maleka-women-edp-100ml', -- Club DE Nuit Maleka Women EDP (Armaf)
    'armaf-club-de-nuit-oud-edp-unisex-by-armaf-105ml', -- Club DE Nuit OUD EDP - Unisex BY Armaf (Armaf)
    'armaf-club-de-nuit-blue-iconic-100ml', -- Club De Nuit Blue Iconic (Armaf)
    'armaf-odisey-aqua-100ml', -- Odisey Aqua (Armaf)
    'armaf-odyssey-intense-100ml', -- Odyssey Intense (Armaf)
    'armaf-odyssey-spectra-unisex-edp-de-armaf-100ml', -- Odyssey Spectra Unisex EDP - DE Armaf (Armaf)
    'azzaro-azzaro-elixir-100ml', -- Azzaro Elixir (Azzaro)
    'azzaro-azzaro-most-want-intense-100ml', -- Azzaro Most Want Intense (Azzaro)
    'bharara-bharara-king-200ml', -- Bharara King (Bharara)
    'bharara-bharara-king-nueva-edicion-2024-100ml', -- Bharara King/nueva Edición 2024 (Bharara)
    'bharara-pharaoh-ramesses-bharara-100ml', -- Pharaoh Ramesses Bharara (Bharara)
    'bharara-roma-wome-bahara-100ml', -- Roma Wome Bahara (Bharara)
    'burberry-burberry-her-tester-100ml', -- Burberry HER Tester (Burberry)
    'carolina-herrera-212-vip-black-ch-tester-100ml', -- 212 VIP Black CH Tester (Carolina Herrera)
    'chanel-bad-boy-le-parfum-for-men-50ml', -- BAD BOY LE Parfum FOR MEN (Carolina Herrera)
    'carolina-herrera-bad-boy-cobalt-elixir-edp-tester-100ml', -- Bad Boy Cobalt Elixir EDP Tester (Carolina Herrera)
    'dior-dior-sauvage-christian-edp-spray-100ml', -- Dior Sauvage Christian EDP Spray (Dior)
    'dolce-gabbana-dolce-gabbana-light-blue-3-3-100ml', -- Dolce Gabbana Light Blue 3.3 (Dolce & Gabbana)
    'por-definir-dumont-nitro-red-for-men-100ml', -- Dumont Nitro RED - For Men (Dumond)
    'emporio-armani-armani-emporio-stronger-with-you-absolutely-eau-de-parfum-100ml', -- Armani Emporio Stronger With You Absolutely Eau De Parfum (Emporio Armani)
    'emporio-armani-emporio-armani-stronger-with-you-intensely-100ml', -- Emporio Armani Stronger With You Intensely (Emporio Armani)
    'emporio-armani-stronger-with-you-intensily-100ml', -- Stronger With YOU Intensily (Emporio Armani)
    'fragrance-world-now-eau-de-parfum-spray-for-women-100ml', -- Now Eau De Parfum Spray For Women (Fragrance World)
    'fragrance-world-now-rave-for-men-100ml', -- Now Rave For Men (Fragrance World)
    'french-avenue-veneno-black-french-avenue-100ml', -- Veneno (black) - French Avenue (French Avenue)
    'giorgio-armani-acqua-di-gio-profundo-eau-de-parfum-100ml', -- Acqua Di Gio Profundo Eau De Parfum (Giorgio Armani)
    'jean-paul-gaultier-jpg-edt-125ml', -- JPG EDT (Jean Paul Gaultier)
    'jean-paul-gaultier-jpg-elixir-tester-125ml', -- JPG Elixir Tester (Jean Paul Gaultier)
    'jean-paul-gaultier-jean-paul-gaultier-le-male-elixir-absolu-eau-de-parfum-125ml', -- Jean Paul Gaultier Le Male Elixir Absolu Eau De Parfum (Jean Paul Gaultier)
    'jean-paul-gaultier-le-beau-le-parfum-125mltester-125ml', -- LE Beau LE Parfum 125mltester (Jean Paul Gaultier)
    'jean-paul-gaultier-le-beau-le-parfum-tester-125ml', -- LE Beau LE Parfum Tester (Jean Paul Gaultier)
    'jean-paul-gaultier-le-male-elixir-125ml', -- LE Male Elixir (Jean Paul Gaultier)
    'jean-paul-gaultier-le-male-elixir-tester-125ml', -- LE Male Elixir Tester (Jean Paul Gaultier)
    'jean-paul-gaultier-let-male-le-parfum-jean-paul-gaultier-125ml', -- LET Male LE Parfum Jean Paul Gaultier (Jean Paul Gaultier)
    'jean-paul-gaultier-let-male-le-parfum-jean-paul-gaultiertester-125ml', -- LET Male LE Parfum Jean Paul Gaultiertester (Jean Paul Gaultier)
    'jean-paul-gaultier-la-belle-le-parfum-eau-de-parfum-tester-100ml', -- La Belle Le Parfum Eau De Parfum Tester (Jean Paul Gaultier)
    'jean-paul-gaultier-scandal-100ml', -- Scandal (Jean Paul Gaultier)
    'jean-paul-gaultier-scandal-absolu-tester-100ml', -- Scandal Absolu Tester (Jean Paul Gaultier)
    'jean-paul-gaultier-scandal-absolu-women-tester-100ml', -- Scandal Absolu Women Tester (Jean Paul Gaultier)
    'jean-paul-gaultier-scandal-jean-paul-gaultier-for-women-100ml', -- Scandal Jean Paul Gaultier For Women (Jean Paul Gaultier)
    'jean-paul-gaultier-scandal-le-parfum-by-jean-paul-gaultier-for-men-100ml', -- Scandal Le Parfum BY Jean Paul Gaultier For Men (Jean Paul Gaultier)
    'jean-paul-gaultier-tester-jean-paul-gaultier-la-belle-paradise-garden-eau-de-parfum-for-women-125ml', -- Tester Jean Paul Gaultier La Belle Paradise Garden Eau De Parfum For Women (Jean Paul Gaultier)
    'lattafa-pride-game-of-spades-diamond-100ml', -- Game OF Spades Diamond (Jo Milano Paris)
    'lattafa-pride-game-of-spades-high-roller-100ml', -- Game Of Spades High Roller (Jo Milano Paris)
    'por-definir-king-of-king-royal-blue-100ml', -- King Of King Royal Blue (King of Kings)
    'lattafa-aether-extrait-for-unisex-100ml', -- Aether Extrait For Unisex (Lattafa)
    'lattafa-atheeri-unisex-by-lattafa-new-launch-100ml', -- Atheeri Unisex - BY Lattafa (new Launch) (Lattafa)
    'lattafa-bade-amethyst-lattafa-100ml', -- Bade Amethyst Lattafa (Lattafa)
    'lattafa-badee-al-oud-oud-for-glory-edp-100mi-100ml', -- Badee Al Oud Oud For Glory EDP - 100mi (Lattafa)
    'lattafa-emeer-lattafa-100ml', -- Emeer Lattafa (Lattafa)
    'lattafa-fakhar-gold-lattafa-100ml', -- Fakhar Gold Lattafa (Lattafa)
    'lattafa-fakhar-platinum-lataffa-unisex-edp-100mi-100ml', -- Fakhar Platinum Lataffa Unisex EDP - 100mi (Lattafa)
    'lattafa-haya-eau-parfum-100ml', -- Haya Eau Parfum (Lattafa)
    'lattafa-hayaati-eau-de-parfum-100ml', -- Hayaati Eau De Parfum (Lattafa)
    'lattafa-hayati-edp-100ml', -- Hayati EDP (Lattafa)
    'lattafa-khanjar-lattafa-100ml', -- Khanjar Lattafa (Lattafa)
    'lattafa-lattafa-5th-anniversary-yara-yara-candy-edp-100ml', -- Lattafa 5th Anniversary Yara & Yara Candy EDP (Lattafa)
    'lattafa-lattafa-afeef-eau-de-parfum-for-everyone-100ml', -- Lattafa Afeef Eau De Parfum For Everyone (Lattafa)
    'lattafa-lattafa-victoria-eau-de-parfum-for-everyone-100ml', -- Lattafa Victoria Eau De Parfum For Everyone (Lattafa)
    'lattafa-nebras-elixir-100ml', -- Nebras Elixir (Lattafa)
    'lattafa-qaed-al-fursan-unlimited-color-blanco-100ml', -- Qaed Al Fursan Unlimited Color Blanco (Lattafa)
    'lattafa-set-de-khamrah-1-1-100ml', -- SET DE Khamrah+1+1 (Lattafa)
    'lattafa-set-de-sublime-lattafa-100ml', -- SET DE Sublime Lattafa (Lattafa)
    'lattafa-shuyukh-gold-100ml', -- Shuyukh Gold (Lattafa)
    'lattafa-shuyukh-silver-100ml', -- Shuyukh Silver (Lattafa)
    'lattafa-teriaq-intense-edp-100ml', -- Teriaq Intense EDP (Lattafa)
    'lattafa-pride-al-qiam-gold-100ml', -- AL Qiam Gold (Lattafa Pride)
    'lattafa-pride-al-qiam-gold-3-piece-perfume-gift-set-by-lattafa-pride-100ml', -- Al Qiam Gold 3-piece Perfume Gift Set BY Lattafa Pride (Lattafa Pride)
    'lattafa-pride-arte-del-universo-unisex-edp-de-lattafa-pride-100ml', -- Arte DEL Universo Unisex EDP - DE Lattafa Pride (Lattafa Pride)
    'lattafa-pride-game-of-spades-royale-gift-set-100ml', -- Game Of Spades Royale Gift Set (Lattafa Pride)
    'lattafa-pride-giftset-art-of-universe-3pc-100ml', -- Giftset Art Of Universe -3pc (Lattafa Pride)
    'lattafa-pride-pride-pisa-100ml', -- Pride Pisa (Lattafa Pride)
    'lattafa-pride-set-game-of-spades-x-3-pcs-x-5-pcs-30ml', -- SET Game OF Spades X 3 PCS + X 5 PCS (Lattafa Pride)
    'mancera-mancera-coco-vainille-4-0-100ml', -- Mancera Coco Vainille 4.0 (Mancera)
    'montale-montale-arabia-tonca-100ml', -- Montale Arabia Tonca (Montale)
    'montale-montale-arabia-tonca-tester-100ml', -- Montale Arabia Tonca Tester (Montale)
    'paco-rabanne-elixir-victory-invictus-tester-100ml', -- Elixir Victory Invictus Tester (Paco Rabanne)
    'paco-rabanne-one-million-gold-for-her-tester-100ml', -- ONE Million Gold FOR HER Tester (Paco Rabanne)
    'paco-rabanne-pacco-rabanne-one-million-lucky-100ml', -- Pacco Rabanne ONE Million Lucky (Paco Rabanne)
    'paco-rabanne-set-de-4-pacco-rabanne-100ml', -- SET DE 4 Pacco Rabanne (Paco Rabanne)
    'paco-rabanne-tester-one-million-gold-elixir-for-men-100ml', -- Tester ONE Million Gold Elixir FOR MEN (Paco Rabanne)
    'paris-corner-marshmallow-blush-paris-corner-100ml', -- Marshmallow Blush Paris Corner (Paris Corner)
    'por-definir-amber-rouge-tester-100ml', -- Amber Rouge Tester (Por Definir)
    'por-definir-choco-overdose-75ml', -- Choco Overdose (Por Definir)
    'por-definir-cookie-crave-75ml', -- Cookie Crave (Por Definir)
    'por-definir-jean-lowe-azure-eau-parfum-100ml', -- Jean Lowe Azure Eau Parfum (Por Definir)
    'por-definir-jean-lowe-inmortal-100ml', -- Jean Lowe Inmortal (Por Definir)
    'por-definir-set-honor-and-glory-1-1-100ml', -- SET Honor AND Glory + 1 +1 (Por Definir)
    'por-definir-set-untold-1-1-100ml', -- SET Untold +1 +1 (Por Definir)
    'por-definir-sher-eau-de-parfum-100ml', -- Sher EAU DE Parfum (Por Definir)
    'por-definir-vulcan-feu-women-edp-100ml', -- Vulcan Feu Women EDP (Por Definir)
    'por-definir-whipped-pleasure-75ml', -- Whipped Pleasure (Por Definir)
    'por-definir-yumyum-island-100ml', -- Yumyum Island (Por Definir)
    'rasasi-ansaam-silver-100ml', -- Ansaam Silver (Rasasi)
    'rasasi-her-confesion-woman-100ml', -- HER Confesion Woman (Rasasi)
    'rasasi-his-confesion-100ml', -- HIS Confesion (Rasasi)
    'rasasi-his-confesion-woman-100ml', -- HIS Confesion Woman (Rasasi)
    'rasasi-hawas-black-100ml', -- Hawas Black (Rasasi)
    'rasasi-hawas-fire-100ml', -- Hawas Fire (Rasasi)
    'rasasi-hawas-tropical-eau-parfum-100ml', -- Hawas Tropical Eau Parfum (Rasasi)
    'rasasi-rasasi-hawas-diva-edp-for-women-100ml', -- Rasasi Hawas Diva EDP For Women (Rasasi)
    'valentino-valentino-garavani-uomo-born-in-roma-extradosis-100ml', -- Valentino Garavani Uomo Born In Roma Extradosis (Valentino)
    'versace-eros-flame-200ml', -- Eros Flame (Versace)
    'versace-versace-eros-edp-200ml', -- Versace Eros EDP (Versace)
    'versace-versace-eros-eau-de-parfum-for-men-edp-100ml', -- Versace Eros Eau De Parfum For Men EDP (Versace)
    'versace-versace-eros-flame-200ml', -- Versace Eros Flame (Versace)
    'xerjoff-erab-pura-xerjof-tester-100ml', -- Erab Pura Xerjof Tester (Xerjoff)
    'xerjoff-erba-pura-xerjof-eau-parfumtester-100ml', -- Erba Pura Xerjof Eau Parfumtester (Xerjoff)
    'xerjoff-torino-21-100ml', -- Torino 21 (Xerjoff)
    'xerjoff-xerjoff-torino-21-unisex-edp-100ml', -- Xerjoff Torino 21 Unisex EDP (Xerjoff)
    'yves-saint-laurent-yves-saint-laurent-myslf-le-parfum-de-100ml' -- Yves Saint Laurent Myslf Le Parfum De (Yves Saint Laurent)
);
